#!/usr/bin/env python3
"""Generate the large-screen resource overrides from the base drawables.

Reads DogAnimationExperiment/resources/drawables/drawables.xml and writes
resources-large-<scale>/drawables/drawables.xml for each entry in LARGE_SCALES:
every icon re-rasterized at that scale's field or battery icon height, and,
unless the scale is 100, every sprite sheet scaled by that percentage (with a
palette taken from the sheet's own pixels).
monkey.jungle maps screen sizes to these folders.

Usage:
  scripts/generate-large-screen-resources.py          # (re)write the files
  scripts/generate-large-screen-resources.py --check  # exit 1 if out of date
"""
import struct
import sys
import xml.etree.ElementTree as ET
import zlib
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent / "DogAnimationExperiment"
BASE_XML = APP_DIR / "resources" / "drawables" / "drawables.xml"

# scale percent -> (field icon height, battery icon height) in px, sized to the
# field-text height of the screens mapped to it in monkey.jungle.
LARGE_SCALES = {100: (26, 33), 200: (29, 37)}

HEADER = (
    "    <!-- GENERATED by scripts/generate-large-screen-resources.py from\n"
    "         resources/drawables/drawables.xml. Do not edit; edit the base file\n"
    "         and re-run the script. Screen sizes are mapped in monkey.jungle. -->"
)


def png_colors(path):
    """Distinct opaque RGB colors in an 8-bit RGBA, non-interlaced PNG."""
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        sys.exit(f"{path}: not a PNG")
    pos, idat, header = 8, b"", None
    while pos < len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + length]
        if ctype == b"IHDR":
            header = struct.unpack(">IIBBBBB", chunk)
        elif ctype == b"IDAT":
            idat += chunk
        pos += 12 + length
    width, height, bit_depth, color_type, _, _, interlace = header
    if (bit_depth, color_type, interlace) != (8, 6, 0):
        sys.exit(f"{path}: expected 8-bit RGBA non-interlaced PNG, got depth={bit_depth} type={color_type} interlace={interlace}")

    raw, bpp, stride = zlib.decompress(idat), 4, width * 4
    prev, colors, i = bytearray(stride), set(), 0
    for _ in range(height):
        filt, line = raw[i], bytearray(raw[i + 1:i + 1 + stride])
        i += 1 + stride
        for x in range(stride):
            a = line[x - bpp] if x >= bpp else 0
            b = prev[x]
            c = prev[x - bpp] if x >= bpp else 0
            if filt == 1:
                line[x] = (line[x] + a) & 0xFF
            elif filt == 2:
                line[x] = (line[x] + b) & 0xFF
            elif filt == 3:
                line[x] = (line[x] + (a + b) // 2) & 0xFF
            elif filt == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[x] = (line[x] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 0xFF
        for x in range(0, stride, 4):
            if line[x + 3] >= 128:
                colors.add("%02X%02X%02X" % (line[x], line[x + 1], line[x + 2]))
        prev = line
    return colors


def generate(scale, field_icon_height, battery_icon_height):
    base = ET.parse(BASE_XML).getroot()
    sprites, icons, palettes = [], [], {}
    for bmp in base.iter("bitmap"):
        filename = bmp.get("filename")
        if filename.endswith("-sheet.png") and scale != 100:
            breed = filename.split("/")[0]
            palettes.setdefault(breed, set()).update(png_colors(BASE_XML.parent / filename))
            sprites.append((bmp.get("id"), filename, breed))
        elif filename.startswith("icons/"):
            base_w, base_h = int(bmp.get("scaleX")), int(bmp.get("scaleY"))
            height = battery_icon_height if bmp.get("id").startswith("IconBattery") else field_icon_height
            icons.append((bmp.get("id"), filename, round(base_w * height / base_h), height))

    lines = [
        '<drawables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:noNamespaceSchemaLocation="https://developer.garmin.com/downloads/connect-iq/resources.xsd">',
        HEADER,
    ]
    for bid, filename, breed in sprites:
        palette = "".join(f"<color>{c}</color>" for c in sorted(palettes[breed]))
        lines.append(
            f'    <bitmap id="{bid}" filename="../../resources/drawables/{filename}" dithering="none" '
            f'compress="true" scaleRelativeTo="image" scaleX="{scale}%" scaleY="{scale}%">'
            f"<palette>{palette}</palette></bitmap>"
        )
    for bid, filename, width, height in icons:
        lines.append(
            f'    <bitmap id="{bid}" filename="../../resources/drawables/{filename}" dithering="none" '
            f'scaleX="{width}" scaleY="{height}" />'
        )
    lines.append("</drawables>")
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    stale = []
    for scale, (field_icon_height, battery_icon_height) in LARGE_SCALES.items():
        out = APP_DIR / f"resources-large-{scale}" / "drawables" / "drawables.xml"
        content = generate(scale, field_icon_height, battery_icon_height)
        if check:
            if not out.exists() or out.read_text() != content:
                stale.append(out)
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content)
            print(f"wrote {out.relative_to(APP_DIR.parent)}")
    if stale:
        for path in stale:
            print(f"out of date: {path.relative_to(APP_DIR.parent)}", file=sys.stderr)
        print("Run scripts/generate-large-screen-resources.py and commit the result.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
